### PR TITLE
Rails4

### PR DESCRIPTION
**Pull request by bgracie**

### CODE REVIEW

**Comment by dhMuse** [comment]
@bgracie Hey, I was hoping you would be able to finish off the few un-checked items in the issue checklists. Most are just checking that framework changes don't impact us. Don't forget we also need to set the new `secret_keybase` before deploying.

**Comment by bgracie** [comment]
@dmusekamp Remember, we don't want to set the secret keybase until after we're sure we don't want to revert.

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html
"Please note that you should wait to set secret_key_base until you have 100% of your userbase on Rails 4.x and are reasonably sure you will not need to rollback to Rails 3.x. "

**Comment by bgracie** [comment]
`exception_notification` is broken for rails 4.0 atm

https://github.com/smartinez87/exception_notification/issues/315

we might need to patch it or find an alternative if they don't make a new release soon

**Comment by bgracie** [comment]
closed with https://github.com/pathwaysmedical/frasernw/commit/fb5eecdf32337b93d34edb961e19ea601e4c9355 (squashed commit)

**Pull request closed without merging**
