### PR TITLE
Remove all aop

### PR DESCRIPTION
**Pull request by bgracie**

### CODE REVIEW

**Comment by KelseyDH** [comment]
Nice, this looks good.  I noticed quite a lot of inline Javascript in `specialist/_form` was removed in this PR, are you sure all of that behaviour in the Specialist edit form is accounted for?  We have quite a few dynamic form events on that page.

**Comment by bgracie** [comment]
Yeah, as far as I can tell Russell just copy pasted most of it..

**Comment by bgracie** [comment]
Unfortunately, ran into a problem testing: (Specialist 187)
- some capacities are still not removed even when all are unchecked
- they show up in the show page, but not the edit form 
--> something's up with the way the input id's are generated...

**Comment by bgracie** [comment]
Testing:
- [ ] Remove all AOP for specialist
- [ ] Add AOP for specialist
- [ ] Review specialist
- [ ] AOP inputs
- [ ] New specialist with AOP

- [ ] Remove all AOP for clinic
- [ ] Add AOP for clinic
- [ ] Review Clinic
- [ ] AOP inputs
- [ ] Clinic attendance inputs
- [ ] New clinic with AOP

**Pull request merged**
